prop:
  filepath: E:/listenfile/

server:
  port: 8082  # 端口号
  servlet:
    context-path: '/front'  #项目访问路径

spring:
  datasource: # 数据源
    url: jdbc:mysql://localhost:3306/novel?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123@qwe
  jackson:
      default-property-inclusion: NON_EMPTY
      date-format: 'yyyy-MM-dd' # 格式化json
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  resources:
    static-locations: classpath:/META- INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

pagehelper: #分页配置
  helper-dialect: mysql
  params:
    count: countSql
  reasonable: false
  support-methods-arguments: true
