prop:
  filepath: E:/listenfile/

server:
  port: 8081  # 端口号
  servlet:
    context-path: '/backstage'  #项目访问路径

spring:
  datasource: # 数据源
    url: jdbc:mysql://localhost:3306/novel?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123@qwe
  jackson:
      date-format: 'yyyy-MM-dd' # 格式化json
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
pagehelper: #分页配置
  helper-dialect: mysql
  params:
    count: countSql
  reasonable: false
  support-methods-arguments: true

